export const GET_BANK_ACCOUNTS_BEGIN =  "GET_BANK_ACCOUNTS_BEGIN"
export const GET_BANK_ACCOUNTS_SUCCESS =  "GET_BANK_ACCOUNTS_SUCCESS"
export const GET_BANK_ACCOUNTS_ERROR =  "GET_BANK_ACCOUNTS_ERROR"

export const VALID_BANK_LOGIN_DEBIT_SUCCESS = "VALID_BANK_LOGIN_DEBIT_SUCCESS" 
export const VALID_BANK_LOGIN_DEBIT_ERROR = "VALID_BANK_LOGIN_DEBIT_ERROR" 

export const LOCKED_ACCOUNT_SUCCESS = "LOCKED_ACCOUNT_SUCCESS"
export const LOCKED_ACCOUNT_ERROR = "LOCKED_ACCOUNT_ERROR"