export const GET_BANK_ACCOUNTS_BEGIN =  "GET_BANK_ACCOUNTS_BEGIN"
export const GET_BANK_ACCOUNTS_SUCCESS =  "GET_BANK_ACCOUNTS_SUCCESS"
export const GET_BANK_ACCOUNTS_ERROR =  "GET_BANK_ACCOUNTS_ERROR"

